# Generated by Django 4.2.3 on 2023-08-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='password',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.IntegerField(default=True),
        ),
    ]
