# Generated by Django 4.2.3 on 2023-08-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_wishlist_password_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.IntegerField(),
        ),
    ]
