# Generated by Django 4.2.1 on 2023-09-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_wishlist_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product", name="stock", field=models.IntegerField(default=30),
        ),
    ]
