# Generated by Django 4.2.1 on 2023-09-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="stock", field=models.IntegerField(default=10),
        ),
    ]
