# Generated by Django 4.2.1 on 2023-09-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetails",
            name="ordered_date",
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(name="Wishlist",),
    ]
