# Generated by Django 4.2.1 on 2023-09-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_orderdetails_ordered_date_delete_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetails",
            name="ordered_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
